# Generated by Django 6.1 on 2026-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_ongoing",
            field=models.BooleanField(default=True),
        ),
    ]
