# Generated by Django 6.1 on 2026-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_project_is_ongoing"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="documentation_photos",),
        migrations.RemoveField(model_name="project", name="is_ongoing",),
        migrations.AddField(
            model_name="project",
            name="project_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project", name="project_url", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
